### ISSUE TITLE
5G Architecture

### ISSUE THREAD

**Issue by edwin-omoigui** [Edwin-programmer/Project5G-ansible-deployment#4]
5G elements and nodes required in architecture
Confirmation of node requirement for testing

**Comment by SamuelHagan-Carleton** [comment]
[5G NS Diagram.docx](https://github.com/Edwin-programmer/Project5G-ansible-deployment/files/5861554/5G.NS.Diagram.docx)

**Comment by SamuelHagan-Carleton** [comment]
Attached is the network architecture for 5G Standalone, Non-Standalone and the proposed lab architecture.

**Comment by edwin-omoigui** [comment]
Completed
